name: parallelize
description: (Parallelism Package Update) An optimized Dart package that simplifies parallelization using isolates.
version: 1.0.0

repository: https://github.com/shady-ti/parallelism/

environment:
  sdk: ^3.0.5

dev_dependencies:
  dart_code_metrics: ^5.7.5
  lints: ^2.0.0
  test: ^1.21.0
